/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'total' : number,
  'customerPhone' : string,
  'customerAddress' : string,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productWeight' : string,
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'price' : number,
}
export interface Product {
  'id' : bigint,
  'weight' : string,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
  'price' : number,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<
    [string, string, string, number, string, string, boolean, ExternalBlob],
    undefined
  >,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'deleteProduct' : ActorMethod<[string, bigint], boolean>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getOrdersByPhone' : ActorMethod<[string], Array<Order>>,
  'placeOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>, number],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[string, bigint, string], boolean>,
  'updateProduct' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      number,
      string,
      string,
      boolean,
      ExternalBlob,
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];